# Generated by Django 5.1 on 2026-02-14 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("class_name", models.CharField(max_length=100)),
                ("division", models.CharField(max_length=10)),
                ("year", models.CharField(max_length=50)),
                ("academic_year", models.CharField(max_length=20)),
                ("section", models.CharField(blank=True, default="", max_length=50)),
                ("excel_file", models.FileField(upload_to="excel_files/")),
                ("total_students", models.IntegerField(default=0)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_files",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.CharField(max_length=10)),
                ("prn", models.CharField(max_length=30)),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, default="", max_length=15)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "parent_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "parent_phone",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                ("address", models.TextField(blank=True, default="")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_photos/"
                    ),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("division", models.CharField(max_length=10)),
                ("year", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("marked", "Edit Marked"),
                            ("resolved", "Resolved"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="students.studentfile",
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "ordering": ["roll_no"],
            },
        ),
        migrations.AddIndex(
            model_name="studentfile",
            index=models.Index(
                fields=["class_name"], name="student_fil_class_n_1ccacb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentfile",
            index=models.Index(
                fields=["division"], name="student_fil_divisio_1a1d7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentfile",
            index=models.Index(fields=["year"], name="student_fil_year_e54cbe_idx"),
        ),
        migrations.AddIndex(
            model_name="studentfile",
            index=models.Index(
                fields=["academic_year"], name="student_fil_academi_519c12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["file"], name="students_file_id_ba2555_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["roll_no"], name="students_roll_no_eef286_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["prn"], name="students_prn_885ea8_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["full_name"], name="students_full_na_365b2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["status"], name="students_status_3ac771_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("file", "roll_no")},
        ),
    ]
